"""rename metadata to mensaje_metadata

Revision ID: d5c2dcd2d98b
Revises: 
Create Date: 2025-04-27 13:13:23.284338+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5c2dcd2d98b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('programa', sa.String(length=100), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=False),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('riesgo_estres', sa.Float(), nullable=True),
    sa.Column('riesgo_desercion', sa.Float(), nullable=True),
    sa.Column('factores_estres', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_table('academic_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('evento', sa.String(length=100), nullable=False),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.Column('promedio', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_history_id'), 'academic_history', ['id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('contexto', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_table('stress_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=True),
    sa.Column('fecha_prediccion', sa.DateTime(), nullable=True),
    sa.Column('nivel_estres', sa.Float(), nullable=False),
    sa.Column('probabilidad_abandono', sa.Float(), nullable=False),
    sa.Column('factores_riesgo', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stress_predictions_id'), 'stress_predictions', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversacion_id', sa.Integer(), nullable=True),
    sa.Column('rol', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('mensaje_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['conversacion_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_stress_predictions_id'), table_name='stress_predictions')
    op.drop_table('stress_predictions')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_academic_history_id'), table_name='academic_history')
    op.drop_table('academic_history')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
